import { readFile } from "node:fs/promises";
import { resolve } from "node:path";
const root = process.cwd();
const readJson = async (path) => JSON.parse(await readFile(resolve(root, path), "utf8"));
const [siteData, pages, navigation, blocks, collections, media] = await Promise.all([readJson("src/data/site.json"),readJson("src/data/pages.json"),readJson("src/data/navigation.json"),readJson("src/data/globalBlocks.json"),readJson("src/data/collections.json"),readJson("src/data/media.json")]);
const errors = [];
const report = (condition, message) => { if (!condition) errors.push(message); };
const ids = new Set(); const slugs = new Set(); const routes = new Set(pages.map((page) => page.slug));
const isExternal = (href = "") => /^(?:https?:|mailto:|tel:)/.test(href) || href.startsWith("#");
const walk = (value, context) => { if (Array.isArray(value)) return value.forEach((item, index) => walk(item, `${context}[${index}]`)); if (!value || typeof value !== "object") return; if (typeof value.href === "string" && !isExternal(value.href)) { const pathname = value.href.split(/[?#]/,1)[0] || "/"; report(routes.has(pathname), `${context} links to unknown route "${value.href}"`); } Object.entries(value).forEach(([key, child]) => walk(child, `${context}.${key}`)); };
const checkEntry = (entry, context) => { if (entry?.ref) { report(Boolean(blocks[entry.ref]), `${context} references missing block "${entry.ref}"`); return; } if (entry?.type === "Section" && entry.source?.collection) report(Array.isArray(collections[entry.source.collection]), `${context} references missing collection "${entry.source.collection}"`); if (entry?.type === "Group") { (entry.blocks ?? []).forEach((item, index) => checkEntry(item, `${context}.blocks[${index}]`)); (entry.panels ?? []).forEach((panel, panelIndex) => (panel.blocks ?? []).forEach((item, index) => checkEntry(item, `${context}.panels[${panelIndex}].blocks[${index}]`))); } };
report(siteData.site?.name?.trim(), "site.name is required"); report(siteData.site?.url?.startsWith("https://"), "site.url must be an absolute HTTPS URL");
for (const page of pages) { report(page.id?.trim(), "every page needs an id"); report(page.slug?.startsWith("/"), `page "${page.id}" needs an absolute slug`); report(!ids.has(page.id), `duplicate page id "${page.id}"`); report(!slugs.has(page.slug), `duplicate page slug "${page.slug}"`); report(page.seo?.title?.trim(), `page "${page.id}" needs an SEO title`); report(page.seo?.description?.trim(), `page "${page.id}" needs an SEO description`); ids.add(page.id); slugs.add(page.slug); (page.blocks ?? []).forEach((entry, index) => checkEntry(entry, `page "${page.id}" block ${index + 1}`)); }
for (const [id, block] of Object.entries(blocks)) { report(block.id === id, `block key "${id}" does not match its id`); if (block.source?.collection) report(Array.isArray(collections[block.source.collection]), `block "${id}" references missing collection "${block.source.collection}"`); }
const mediaRefs = new Set(); const collectMedia = (value) => { if (Array.isArray(value)) return value.forEach(collectMedia); if (!value || typeof value !== "object") return; if (typeof value.media === "string") mediaRefs.add(value.media); if (Array.isArray(value.media)) value.media.forEach((ref) => mediaRefs.add(ref)); Object.values(value).forEach(collectMedia); };
collectMedia(blocks); collectMedia(collections); mediaRefs.forEach((ref) => report(Boolean(media[ref]), `missing media record "${ref}"`)); for (const [id, item] of Object.entries(media)) { report(item.id === id, `media key "${id}" does not match its id`); report(item.alt?.trim(), `media "${id}" needs alternative text`); }
walk(blocks, "globalBlocks"); walk(collections, "collections"); walk(navigation, "navigation");
if (errors.length) { console.error("\nContent audit failed:\n"); errors.forEach((error) => console.error(`- ${error}`)); process.exitCode = 1; } else console.log(`Content audit passed: ${pages.length} pages, ${Object.keys(blocks).length} blocks, ${Object.keys(media).length} media records.`);
